* Support for later completion of task and resources added. By writing 'supplement task <ID> { ... }' an already defined task can be extended. So it's easier now to create a file which contains the vacations for all resources seperate from the resource definition itself.
* Extended expression parser to work on string type values as
well.

* Logical expressions for hidetask, rolluptask etc. can now
contain functions as well. Currently there is support for 'istask',
'issubtaskof', 'contains', 'ismilestone'.

* Moved the docs directory from taskjugger subdir to topdir.

* Added feature list and changelog to the documentation.

* Property reference is now sorted in alphabetical order.

* Added missing 'export' report to documentation.


git-svn-id: https://www.taskjuggler.org/svn/taskjuggler/trunk@137 e1914e07-63f8-0310-9059-d6d858d7cdca

diff --git a/TestSuite/testdir b/TestSuite/testdir
--- a/TestSuite/testdir
+++ b/TestSuite/testdir
@@ -2,26 +2,36 @@
 
 set errors=0
 
+function do_testing
+{
+  f=$1
+  op=$2
+  echo "Running test $f" >> log
+  ../../taskjuggler/taskjuggler $f 2>> log
+  if [ $? $op 0 ]; then
+    errors=$(( $errors + 1 ))
+    echo "Test $f failed!"
+  fi
+  checkscript=`echo $f | sed s/\\\\\(.*\\\\\).tjp/\\\1.sh/g`
+  if [ -x $checkscript ] ; then
+    sh $checkscript
+    if [ $? -ne 0 ] ; then
+      errors=$(( $errors + 1 ))
+      echo "Text $f failed (check script)!"
+    fi
+  fi
+}
+
 rm -f log
 touch log
 
 for f in Correct/*.tjp ; do
-  echo "Running test $f" >> log
-  ../../taskjuggler/taskjuggler $f 2>> log
-  if [ $? -ne 0 ]; then
-    errors=$(( $errors + 1 ))
-    echo "Test $f failed!"
-  fi
+  do_testing $f -ne
 done
-  
+ 
 for f in Errors/*.tjp ; do
-  echo "Running test $f" >> log
-  ../../taskjuggler/taskjuggler $f 2>> log
-  if [ $? -eq 0 ]; then
-    errors=$(( $errors + 1 ))
-    echo "Test $f failed!"
-  fi
+  do_testing $f -eq
 done
-
+ 
 exit $errors
 
