- Partial fix for timezone handling. - export reports now support resource usage export - documentation updated - extended test suite to contain arbitrary tests in Misc directory - changed version number to 1.1 (getting ready for next release)
git-svn-id: https://www.taskjuggler.org/svn/taskjuggler/trunk@140 e1914e07-63f8-0310-9059-d6d858d7cdca

diff --git a/TestSuite/Misc/testdir b/TestSuite/Misc/testdir
--- a/TestSuite/Misc/testdir
+++ b/TestSuite/Misc/testdir
@@ -6,18 +6,15 @@ dirs=`find * -type d -maxdepth 0`
 
 for d in $dirs ; do
   if [ $d != "CVS" ] ; then
-    echo "Testing in $d"
     cd $d
-    if [ -x ./testdir ] ; then
-      ./testdir
-    else
-      ../testdir
-    fi
+    ./runtest
     errors=$(( $errors + $? ))
+    if [ $? -ne 0 ] ; then
+      echo "Test $d failed"
+    fi
     cd ..
   fi
 done
 
-echo $errors test failed!
 exit $errors
 
